"""
SkillForge AI — RAG Career Assistant Page.

Interactive chat interface powered by Retrieval-Augmented Generation (RAG).
Allows users to ask career questions grounded in their uploaded resume,
target job description, and career knowledge base.
"""

from __future__ import annotations

import sys
from pathlib import Path

import streamlit as st

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from config.settings import get_settings
from src.skillforge.ai.llm.factory import create_llm_provider
from src.skillforge.models.rag import CitationSource, ConversationRole
from src.skillforge.services.rag_assistant import RAGAssistant
from src.skillforge.services.retrieval_service import RetrievalService
from src.skillforge.utils.exceptions import SkillForgeError
from src.skillforge.utils.logging import logger

st.set_page_config(page_title="Career Assistant | SkillForge AI", page_icon="💬", layout="wide")


@st.cache_resource
def get_rag_assistant() -> RAGAssistant:
    """Create a cached RAGAssistant instance shared across reruns."""
    settings = get_settings()
    retrieval_service = RetrievalService()

    # Automatically index knowledge base markdown files
    kb_path = PROJECT_ROOT / "knowledge_base"
    if kb_path.exists():
        retrieval_service.index_knowledge_base_directory(kb_path)

    # Instantiate LLM provider (falls back gracefully to Mock if no key configured)
    try:
        if settings.active_api_key:
            provider = create_llm_provider()
        else:
            provider = create_llm_provider(
                "mock",
                default_response=(
                    "I am currently running in offline demonstration mode (no API key configured). "
                    "In production with a Gemini or Groq key, this answer is fully generated by the LLM "
                    "and strictly grounded in the retrieved sources listed below."
                ),
            )
    except Exception:
        provider = create_llm_provider("mock")

    return RAGAssistant(retrieval_service=retrieval_service, llm_provider=provider)


# ── Session State Initialization ──────────────────────────────────────

if "messages" not in st.session_state:
    st.session_state.messages = []
if "resume_indexed" not in st.session_state:
    st.session_state.resume_indexed = False
if "jd_indexed" not in st.session_state:
    st.session_state.jd_indexed = False

assistant = get_rag_assistant()

# ── Synchronize Uploaded Resume & JD to Vector Store ───────────────────

resume = st.session_state.get("resume_analysis")
job_desc = st.session_state.get("job_description", "")
target_role = st.session_state.get("target_role", "")

if resume and not st.session_state.resume_indexed:
    assistant.retrieval_service.index_resume(
        resume=resume,
        filename=getattr(resume, "filename", "resume.pdf"),
    )
    st.session_state.resume_indexed = True

if job_desc.strip() and not st.session_state.jd_indexed:
    assistant.retrieval_service.index_job_description(
        job_description=job_desc,
        title=target_role or "Target Job Description",
    )
    st.session_state.jd_indexed = True

# ── Page Header ────────────────────────────────────────────────────────

st.title("💬 RAG Career Assistant")
st.markdown(
    "Ask questions grounded in your **resume**, **job description**, "
    "and **curated career knowledge base**. Every answer cites its exact source documents."
)

# ── Sidebar Status & Controls ──────────────────────────────────────────

with st.sidebar:
    st.subheader("📚 Active Knowledge Sources")
    status = assistant.retrieval_service.get_status()

    st.markdown(f"**Total Indexed Chunks:** `{status['total_chunks']}`")
    for ns, count in status["namespaces"].items():
        icon = "📄" if ns == "resume" else ("💼" if ns == "job_description" else "📖")
        st.markdown(f"- {icon} `{ns}`: {count} chunks")

    st.divider()
    source_filter = st.radio(
        "🎯 Search Target:",
        ["All Sources", "My Resume", "Job Description", "Career Guides"],
        index=0,
    )

    if st.button("🧹 Clear Conversation", use_container_width=True):
        st.session_state.messages = []
        assistant.history.clear()
        st.rerun()

# ── Render Conversation History ────────────────────────────────────────

for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])
        if msg.get("sources"):
            with st.expander(f"📌 Grounding Sources ({len(msg['sources'])})", expanded=False):
                for src in msg["sources"]:
                    st.markdown(
                        f"**[{src.source_type.value.title()}]** `{src.source_name}` "
                        f"{f'• Section: *{src.section}*' if src.section else ''} "
                        f"*(Relevance: {src.relevance_score:.2f})*"
                    )
                    st.caption(f"> {src.content_preview}")
                    st.divider()

# ── Chat Input & RAG Execution ─────────────────────────────────────────

if prompt := st.chat_input("Ask a question (e.g. 'How should I answer behavioral interview questions?')"):
    # Render user message
    st.session_state.messages.append({"role": "user", "content": prompt})
    with st.chat_message("user"):
        st.markdown(prompt)

    # Determine sources based on radio filter
    target_sources = None
    if source_filter == "My Resume":
        target_sources = [CitationSource.RESUME]
    elif source_filter == "Job Description":
        target_sources = [CitationSource.JOB_DESCRIPTION]
    elif source_filter == "Career Guides":
        target_sources = [CitationSource.KNOWLEDGE_BASE]

    # Generate grounded response
    with st.chat_message("assistant"):
        with st.spinner("🔍 Searching vector store & generating grounded response..."):
            try:
                response = assistant.query(
                    question=prompt,
                    sources=target_sources,
                    top_k=4,
                    session_context={"target_role": target_role},
                )

                st.markdown(response.answer)

                if response.sources:
                    with st.expander(f"📌 Grounding Sources ({len(response.sources)})", expanded=True):
                        for src in response.sources:
                            st.markdown(
                                f"**[{src.source_type.value.title()}]** `{src.source_name}` "
                                f"{f'• Section: *{src.section}*' if src.section else ''} "
                                f"*(Relevance: {src.relevance_score:.2f})*"
                            )
                            st.caption(f"> {src.content_preview}")
                            st.divider()

                # Save assistant response to session state
                st.session_state.messages.append(
                    {
                        "role": "assistant",
                        "content": response.answer,
                        "sources": response.sources,
                    }
                )

            except Exception as e:
                st.error(f"❌ Error generating response: {e}")
                logger.exception("RAG Assistant query error")
